version: 2.1

parameters:
    GHA_Actor:
        type: string
        default: ''
    GHA_Action:
        type: string
        default: ''
    GHA_Event:
        type: string
        default: ''
    GHA_Meta:
        type: string
        default: ''

executors:
    node_16_executor:
        working_directory: /tmp/extras
        docker:
            - image: cimg/node:16.17.1
              environment:
                  NODE_OPTIONS: --max_old_space_size=6144
        resource_class: 'large'

orbs:
    git-shallow-clone: guitarrapc/git-shallow-clone@2.4.1

jobs:
    build:
        executor: node_16_executor
        steps:
            - git-shallow-clone/checkout_advanced:
                  clone_options: '--depth 1 --verbose'
            - restore_cache:
                  name: Restore Yarn cache
                  keys:
                      - build-all-{{ checksum "code/yarn.lock" }}--{{ checksum "scripts/yarn.lock" }}
            - run:
                  name: Install
                  command: yarn install
            - save_cache:
                  name: Save Yarn cache
                  key: build-all-{{ checksum "code/yarn.lock" }}--{{ checksum "scripts/yarn.lock" }}
                  paths:
                      - ~/.yarn/berry/cache
            - run:
                  name: Build
                  command: yarn build
    demo:
        executor: node_16_executor
        steps:
            - git-shallow-clone/checkout_advanced:
                  clone_options: '--depth 1 --verbose'
            - restore_cache:
                  name: Restore Yarn cache
                  keys:
                      - build-demo-{{ checksum "code/yarn.lock" }}--{{ checksum "scripts/yarn.lock" }}
            - run:
                  name: Install
                  command: yarn install
            - save_cache:
                  name: Save Yarn cache
                  key: build-demo-{{ checksum "code/yarn.lock" }}--{{ checksum "scripts/yarn.lock" }}
                  paths:
                      - ~/.yarn/berry/cache
            - run:
                  name: Build
                  command: yarn build:all

workflows:
    pull_request:
        when:
            and:
                - equal: ["pull_request", << pipeline.parameters.GHA_Action >>]
        jobs:
            - build
            - demo:
                requires:
                    - build